"""empty message

Revision ID: 5ada958a78db
Revises: 012a66ee31f7
Create Date: 2016-10-02 10:13:26.529815

"""

# revision identifiers, used by Alembic.
revision = '5ada958a78db'
down_revision = '012a66ee31f7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('created_time', sa.String(), nullable=True))
    op.add_column('comments', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'user_id')
    op.drop_column('comments', 'created_time')
    ### end Alembic commands ###
